### Delete a person
DELETE https://phone-book-backend-dlis.onrender.com/api/persons/68fb1b43fc8490c29b736331

###
POST  https://phone-book-backend-dlis.onrender.com/api/persons
Content-Type: application/json

{
  "name": "maddy-2",
  "number": "12666"
}

### Get all persons
GET https://phone-book-backend-dlis.onrender.com/api/persons

### Get all persons id
GET https://phone-book-backend-dlis.onrender.com/api/persons/68fa29dbff2e8b2e95d74eec

### update a person
PUT  https://phone-book-backend-dlis.onrender.com/api/persons/68fa29dbff2e8b2e95d74eec
Content-Type: application/json

{
  
  "number": "987-65411"
}